version: '2'
services:
  elasticsearch1:
    image: my-elasticsearch
    container_name: elasticsearch1
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - node.name=elasticsearch1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms500m -Xmx500m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  elasticsearch2:
    image: my-elasticsearch
    container_name: elasticsearch2
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - node.name=elasticsearch2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms500m -Xmx500m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    ports:
      - 9301:9300
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
