version: '2'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    container_name: elasticsearch1
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - node.name=elasticsearch1
      - bootstrap.memory_lock=true
      - "discovery.zen.ping.unicast.hosts=elasticsearch2,elasticsearch3"
      - "ES_JAVA_OPTS=-Xms22000m -Xmx22000m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 50g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    container_name: elasticsearch2
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - node.name=elasticsearch2
      - bootstrap.memory_lock=true
      - "discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch3"
      - "ES_JAVA_OPTS=-Xms22000m -Xmx22000m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 50g
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9301:9300
    networks:
      - esnet
  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    container_name: elasticsearch3
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - node.name=elasticsearch3
      - bootstrap.memory_lock=true
      - "discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch2"
      - "ES_JAVA_OPTS=-Xms22000m -Xmx22000m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 50g
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9302:9300
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local
networks:
  esnet: