version: '2'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    container_name: elasticsearch1
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - node.name=elasticsearch1
      - bootstrap.memory_lock=true
      - path.data=/tank/elasticsearch/data
      - "ES_JAVA_OPTS=-Xms30000m -Xmx30000m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 60g
    volumes:
      - esdata1:/tank/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    container_name: elasticsearch2
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - node.name=elasticsearch2
      - bootstrap.memory_lock=true
      - path.data=/tank/elasticsearch/data
      - "ES_JAVA_OPTS=-Xms30000m -Xmx30000m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 60g
    volumes:
      - esdata2:/tank/elasticsearch/data
    ports:
      - 9301:9300
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
networks:
  esnet: